---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_prometheus].
  rabbitmq.conf: |
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      loopback_users.guest = false
      cluster_formation.k8s.service_name = rabbitmq-service
      cluster_formation.k8s.hostname_suffix = .rabbitmq-service.default.svc.cluster.local
      management.path_prefix = /rabbitmq
      default_user = rabbitmq
      default_pass = rabbitmq
