apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-client-secret
type: Opaque
data:
  # decode instruction: decode it at https://www.base64encode.org/
  spring-rabbitmq-host: cmFiYml0bXEtbWFuYWdlbWVudC1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw=
  spring-rabbitmq-username: UmFiYml0QDEyMw==
  spring-rabbitmq-password: UmFiYml0QDEyMw==
