apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-publisher-service
spec:
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: rabbitmq-publisher
  type: LoadBalancer
